# Generated by Django 6.0.3 on 2026-08-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('TRANSFERRED', 'Transferred'), ('COMMENTED', 'Commented'), ('MENTIONED', 'Mentioned'), ('STATUS_CHANGED', 'Status Changed'), ('ATTACHMENT_UPLOADED', 'Attachment Uploaded')], default='CREATED', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
