# Generated by Django 4.2.30 on 2026-08-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['ticket', '-timestamp'], name='audit_logs__ticket__a61951_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor', '-timestamp'], name='audit_logs__actor_i_c4672c_idx'),
        ),
    ]
