# Generated by Django 6.0.3 on 2026-08-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='Unique identifier e.g. custom_sprint_name', max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text Input'), ('TEXTAREA', 'Textarea'), ('RICH_TEXT', 'Rich Text Editor'), ('NUMBER', 'Number'), ('EMAIL', 'Email'), ('PHONE', 'Phone Number'), ('DATE', 'Date Picker'), ('DATETIME', 'Date Time Picker'), ('DROPDOWN', 'Dropdown'), ('SEARCHABLE_DROPDOWN', 'Searchable Dropdown'), ('MULTI_SELECT', 'Multi-Select Dropdown'), ('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio Button'), ('TOGGLE', 'Toggle Switch'), ('USER_PICKER', 'User Picker'), ('GROUP_PICKER', 'Group Picker'), ('IMAGE_UPLOAD', 'Image Upload'), ('FILE_UPLOAD', 'File Upload'), ('COLOR_PICKER', 'Color Picker')], default='TEXT', max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, help_text='List of choices for dropdowns/radio/checkbox', null=True)),
                ('validation_rules', models.JSONField(blank=True, help_text='Min length, max length, regex pattern, min/max values', null=True)),
                ('conditional_logic', models.JSONField(blank=True, help_text='Show if field X == value Y', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
