# Generated by Django 6.0.3 on 2026-08-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_fields', '0001_initial'),
        ('groups_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='groups_app.group'),
        ),
    ]
