# Generated by Django 6.0.3 on 2026-08-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size_bytes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='is_compressed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='ticketcustomfieldvalue',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
