# Generated by Django 4.2.30 on 2026-08-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_created_at_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acceptance_criteria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
