# Generated by Django 4.2.30 on 2026-08-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_acceptance_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('REOPEN', 'Reopen'), ('DONE', 'Done'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
