# Generated by Django 4.2.30 on 2026-08-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_group', 'status'], name='tickets_tic_assigne_be9672_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_user', 'status'], name='tickets_tic_assigne_2df442_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reporter', 'status'], name='tickets_tic_reporte_f395fc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at', 'priority'], name='tickets_tic_created_e6ae90_idx'),
        ),
    ]
